name: Create models list
run-name: ${{ github.actor }} is testing getting models list working on groq
on: workflow_dispatch
env:
  groq_env_key: ${{ secrets.GROQ_API_KEY }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
          pip install -r requirements.txt
    - name: Run script
      run: python create_models_dict.py
    - name: Commit and push CSV file
      run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Add generated CSV file'
          git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
